// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// deflXCforR
List deflXCforR(Eigen::VectorXd comp, Eigen::MatrixXd K);
RcppExport SEXP _PMlsspca_deflXCforR(SEXP compSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type comp(compSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(deflXCforR(comp, K));
    return rcpp_result_gen;
END_RCPP
}
// makeVexpC
List makeVexpC(Eigen::MatrixXd A, Eigen::MatrixXd S);
RcppExport SEXP _PMlsspca_makeVexpC(SEXP ASEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(makeVexpC(A, S));
    return rcpp_result_gen;
END_RCPP
}
// mkvexpfirstCompSC
double mkvexpfirstCompSC(Eigen::VectorXd a, Eigen::MatrixXd S);
RcppExport SEXP _PMlsspca_mkvexpfirstCompSC(SEXP aSEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type a(aSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(mkvexpfirstCompSC(a, S));
    return rcpp_result_gen;
END_RCPP
}
// makeVexpSC
List makeVexpSC(Eigen::MatrixXd A, Eigen::MatrixXd S);
RcppExport SEXP _PMlsspca_makeVexpSC(SEXP ASEXP, SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(makeVexpSC(A, S));
    return rcpp_result_gen;
END_RCPP
}
// MkCorCompMat
Eigen::MatrixXd MkCorCompMat(Eigen::MatrixXd A, Eigen::MatrixXd S, int d);
RcppExport SEXP _PMlsspca_MkCorCompMat(SEXP ASEXP, SEXP SSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type S(SSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(MkCorCompMat(A, S, d));
    return rcpp_result_gen;
END_RCPP
}
// aatC
Eigen::MatrixXd aatC(Eigen::Map<Eigen::MatrixXd > A);
RcppExport SEXP _PMlsspca_aatC(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(aatC(A));
    return rcpp_result_gen;
END_RCPP
}
// ataC
Eigen::MatrixXd ataC(Eigen::Map<Eigen::MatrixXd > A);
RcppExport SEXP _PMlsspca_ataC(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type A(ASEXP);
    rcpp_result_gen = Rcpp::wrap(ataC(A));
    return rcpp_result_gen;
END_RCPP
}
// atbC
Eigen::MatrixXd atbC(Eigen::Map<Eigen::MatrixXd > A, Eigen::Map<Eigen::MatrixXd > B);
RcppExport SEXP _PMlsspca_atbC(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(atbC(A, B));
    return rcpp_result_gen;
END_RCPP
}
// abC
Eigen::MatrixXd abC(Eigen::Map<Eigen::MatrixXd > A, Eigen::Map<Eigen::MatrixXd > B);
RcppExport SEXP _PMlsspca_abC(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(abC(A, B));
    return rcpp_result_gen;
END_RCPP
}
// abtC
Eigen::MatrixXd abtC(Eigen::Map<Eigen::MatrixXd > A, Eigen::Map<Eigen::MatrixXd > B);
RcppExport SEXP _PMlsspca_abtC(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(abtC(A, B));
    return rcpp_result_gen;
END_RCPP
}
// atdaC
Eigen::MatrixXd atdaC(Eigen::Map<Eigen::MatrixXd > A, Eigen::Map<Eigen::MatrixXd > D);
RcppExport SEXP _PMlsspca_atdaC(SEXP ASEXP, SEXP DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type D(DSEXP);
    rcpp_result_gen = Rcpp::wrap(atdaC(A, D));
    return rcpp_result_gen;
END_RCPP
}
// atdbC
Eigen::MatrixXd atdbC(Eigen::Map<Eigen::MatrixXd > A, Eigen::Map<Eigen::MatrixXd > D, Eigen::Map<Eigen::MatrixXd > B);
RcppExport SEXP _PMlsspca_atdbC(SEXP ASEXP, SEXP DSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type D(DSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(atdbC(A, D, B));
    return rcpp_result_gen;
END_RCPP
}
// avC
Eigen::VectorXd avC(Eigen::MatrixXd A, Eigen::VectorXd v);
RcppExport SEXP _PMlsspca_avC(SEXP ASEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(avC(A, v));
    return rcpp_result_gen;
END_RCPP
}
// vtaC
Eigen::VectorXd vtaC(Eigen::MatrixXd A, Eigen::VectorXd v);
RcppExport SEXP _PMlsspca_vtaC(SEXP ASEXP, SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(vtaC(A, v));
    return rcpp_result_gen;
END_RCPP
}
// vtvC
double vtvC(Eigen::VectorXd v);
RcppExport SEXP _PMlsspca_vtvC(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(vtvC(v));
    return rcpp_result_gen;
END_RCPP
}
// vtuC
double vtuC(Eigen::VectorXd v, Eigen::VectorXd u);
RcppExport SEXP _PMlsspca_vtuC(SEXP vSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type v(vSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(vtuC(v, u));
    return rcpp_result_gen;
END_RCPP
}
// scaleC
Eigen::ArrayXXd scaleC(Eigen::Map<Eigen::MatrixXd> A, bool center, bool scale);
RcppExport SEXP _PMlsspca_scaleC(SEXP ASEXP, SEXP centerSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< bool >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleC(A, center, scale));
    return rcpp_result_gen;
END_RCPP
}
// scaleColsC
Eigen::MatrixXd scaleColsC(Eigen::Map<Eigen::MatrixXd > A, int normtype, Eigen::Map<Eigen::VectorXd > sig);
RcppExport SEXP _PMlsspca_scaleColsC(SEXP ASEXP, SEXP normtypeSEXP, SEXP sigSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type A(ASEXP);
    Rcpp::traits::input_parameter< int >::type normtype(normtypeSEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd > >::type sig(sigSEXP);
    rcpp_result_gen = Rcpp::wrap(scaleColsC(A, normtype, sig));
    return rcpp_result_gen;
END_RCPP
}
// sortC
NumericVector sortC(NumericVector v);
RcppExport SEXP _PMlsspca_sortC(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(sortC(v));
    return rcpp_result_gen;
END_RCPP
}
// sumdiagC
double sumdiagC(Eigen::Map<Eigen::MatrixXd > S);
RcppExport SEXP _PMlsspca_sumdiagC(SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd > >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(sumdiagC(S));
    return rcpp_result_gen;
END_RCPP
}
// EigenC
List EigenC(Eigen::Map<Eigen::MatrixXd> S);
RcppExport SEXP _PMlsspca_EigenC(SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(EigenC(S));
    return rcpp_result_gen;
END_RCPP
}
// GenEigenC
List GenEigenC(Eigen::Map<Eigen::MatrixXd> A, Eigen::Map<Eigen::MatrixXd> B);
RcppExport SEXP _PMlsspca_GenEigenC(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type A(ASEXP);
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(GenEigenC(A, B));
    return rcpp_result_gen;
END_RCPP
}
// solveC
Eigen::MatrixXd solveC(Eigen::MatrixXd S);
RcppExport SEXP _PMlsspca_solveC(SEXP SSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type S(SSEXP);
    rcpp_result_gen = Rcpp::wrap(solveC(S));
    return rcpp_result_gen;
END_RCPP
}
// vifSC
Eigen::VectorXd vifSC(Eigen::Map<Eigen::MatrixXd> S, Eigen::VectorXi ind);
RcppExport SEXP _PMlsspca_vifSC(SEXP SSEXP, SEXP indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type S(SSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type ind(indSEXP);
    rcpp_result_gen = Rcpp::wrap(vifSC(S, ind));
    return rcpp_result_gen;
END_RCPP
}
// vifSPseudoC
Eigen::VectorXd vifSPseudoC(Eigen::Map<Eigen::MatrixXd> S, Eigen::VectorXi ind);
RcppExport SEXP _PMlsspca_vifSPseudoC(SEXP SSEXP, SEXP indSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type S(SSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXi >::type ind(indSEXP);
    rcpp_result_gen = Rcpp::wrap(vifSPseudoC(S, ind));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PMlsspca_deflXCforR", (DL_FUNC) &_PMlsspca_deflXCforR, 2},
    {"_PMlsspca_makeVexpC", (DL_FUNC) &_PMlsspca_makeVexpC, 2},
    {"_PMlsspca_mkvexpfirstCompSC", (DL_FUNC) &_PMlsspca_mkvexpfirstCompSC, 2},
    {"_PMlsspca_makeVexpSC", (DL_FUNC) &_PMlsspca_makeVexpSC, 2},
    {"_PMlsspca_MkCorCompMat", (DL_FUNC) &_PMlsspca_MkCorCompMat, 3},
    {"_PMlsspca_aatC", (DL_FUNC) &_PMlsspca_aatC, 1},
    {"_PMlsspca_ataC", (DL_FUNC) &_PMlsspca_ataC, 1},
    {"_PMlsspca_atbC", (DL_FUNC) &_PMlsspca_atbC, 2},
    {"_PMlsspca_abC", (DL_FUNC) &_PMlsspca_abC, 2},
    {"_PMlsspca_abtC", (DL_FUNC) &_PMlsspca_abtC, 2},
    {"_PMlsspca_atdaC", (DL_FUNC) &_PMlsspca_atdaC, 2},
    {"_PMlsspca_atdbC", (DL_FUNC) &_PMlsspca_atdbC, 3},
    {"_PMlsspca_avC", (DL_FUNC) &_PMlsspca_avC, 2},
    {"_PMlsspca_vtaC", (DL_FUNC) &_PMlsspca_vtaC, 2},
    {"_PMlsspca_vtvC", (DL_FUNC) &_PMlsspca_vtvC, 1},
    {"_PMlsspca_vtuC", (DL_FUNC) &_PMlsspca_vtuC, 2},
    {"_PMlsspca_scaleC", (DL_FUNC) &_PMlsspca_scaleC, 3},
    {"_PMlsspca_scaleColsC", (DL_FUNC) &_PMlsspca_scaleColsC, 3},
    {"_PMlsspca_sortC", (DL_FUNC) &_PMlsspca_sortC, 1},
    {"_PMlsspca_sumdiagC", (DL_FUNC) &_PMlsspca_sumdiagC, 1},
    {"_PMlsspca_EigenC", (DL_FUNC) &_PMlsspca_EigenC, 1},
    {"_PMlsspca_GenEigenC", (DL_FUNC) &_PMlsspca_GenEigenC, 2},
    {"_PMlsspca_solveC", (DL_FUNC) &_PMlsspca_solveC, 1},
    {"_PMlsspca_vifSC", (DL_FUNC) &_PMlsspca_vifSC, 2},
    {"_PMlsspca_vifSPseudoC", (DL_FUNC) &_PMlsspca_vifSPseudoC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PMlsspca(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
