# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deflXCforR <- function(comp, K) {
    .Call('_PMlsspca_deflXCforR', PACKAGE = 'PMlsspca', comp, K)
}

makeVexpC <- function(A, S) {
    .Call('_PMlsspca_makeVexpC', PACKAGE = 'PMlsspca', A, S)
}

mkvexpfirstCompSC <- function(a, S) {
    .Call('_PMlsspca_mkvexpfirstCompSC', PACKAGE = 'PMlsspca', a, S)
}

MkCorCompMat <- function(A, S, d = 0L) {
    .Call('_PMlsspca_MkCorCompMat', PACKAGE = 'PMlsspca', A, S, d)
}

aatC <- function(A) {
    .Call('_PMlsspca_aatC', PACKAGE = 'PMlsspca', A)
}

ataC <- function(A) {
    .Call('_PMlsspca_ataC', PACKAGE = 'PMlsspca', A)
}

atbC <- function(A, B) {
    .Call('_PMlsspca_atbC', PACKAGE = 'PMlsspca', A, B)
}

abC <- function(A, B) {
    .Call('_PMlsspca_abC', PACKAGE = 'PMlsspca', A, B)
}

abtC <- function(A, B) {
    .Call('_PMlsspca_abtC', PACKAGE = 'PMlsspca', A, B)
}

atdaC <- function(A, D) {
    .Call('_PMlsspca_atdaC', PACKAGE = 'PMlsspca', A, D)
}

atdbC <- function(A, D, B) {
    .Call('_PMlsspca_atdbC', PACKAGE = 'PMlsspca', A, D, B)
}

avC <- function(A, v) {
    .Call('_PMlsspca_avC', PACKAGE = 'PMlsspca', A, v)
}

vtaC <- function(A, v) {
    .Call('_PMlsspca_vtaC', PACKAGE = 'PMlsspca', A, v)
}

vtvC <- function(v) {
    .Call('_PMlsspca_vtvC', PACKAGE = 'PMlsspca', v)
}

vtuC <- function(v, u) {
    .Call('_PMlsspca_vtuC', PACKAGE = 'PMlsspca', v, u)
}

scaleC <- function(A, center = TRUE, scale = TRUE) {
    .Call('_PMlsspca_scaleC', PACKAGE = 'PMlsspca', A, center, scale)
}

scaleColsC <- function(A, normtype, sig) {
    .Call('_PMlsspca_scaleColsC', PACKAGE = 'PMlsspca', A, normtype, sig)
}

sortC <- function(v) {
    .Call('_PMlsspca_sortC', PACKAGE = 'PMlsspca', v)
}

sumdiagC <- function(S) {
    .Call('_PMlsspca_sumdiagC', PACKAGE = 'PMlsspca', S)
}

EigenC <- function(S) {
    .Call('_PMlsspca_EigenC', PACKAGE = 'PMlsspca', S)
}

GenEigenC <- function(A, B) {
    .Call('_PMlsspca_GenEigenC', PACKAGE = 'PMlsspca', A, B)
}

solveC <- function(S) {
    .Call('_PMlsspca_solveC', PACKAGE = 'PMlsspca', S)
}

vifSC <- function(S, ind) {
    .Call('_PMlsspca_vifSC', PACKAGE = 'PMlsspca', S, ind)
}

vifSPseudoC <- function(S, ind) {
    .Call('_PMlsspca_vifSPseudoC', PACKAGE = 'PMlsspca', S, ind)
}

